=== Hamzamshoaib/us2/Assignment 1/Assignment_1_337453/WebContent/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="AuctionItems">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="AuctionItem" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Title">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="0"/>
                                        <xs:maxLength value="100"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Category" type="xs:string"/>
                            <xs:element name="Picture" type="xs:anyURI"/>
                            <xs:element name="Description">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="0"/>
                                        <xs:maxLength value="1000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="PostalAddress">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="streetAddress"/>
                                        <xs:element type="xs:string" name="city"/>
                                        <xs:element type="xs:string" name="state"/>
                                        <xs:element type="xs:string" name="country"/>
                                        <xs:element type="xs:short" name="postalCode"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ReservePrice">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="currency" type="currencyType"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="BiddingStartPrice">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:decimal">
                                            <xs:attribute name="currency" type="currencyType"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="BiddingIncrements" type="xs:decimal"/>
                            <xs:element name="EndTime" type="xs:date"/>
                            <xs:element name="ID" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="currencyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GBP"/>
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="USD"/>
            <xs:enumeration value="AUD"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Hamzamshoaib/us2/Assignment 1/Assignment_1_337453/WebContent/database.xml
<?xml version="1.0" encoding="utf-8"?>

<AuctionItems xmlns="http://www.nhl.com"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.nhl.com WebContent/schema.xsd">
    <AuctionItem>
        <Title>Cat Ragdoll</Title>
        <Category>Pets</Category>
        <Picture>https://38.media.tumblr.com/avatar_ff3111cad307_128.png</Picture>
        <Description>He is a very friendly cat</Description>
        <PostalAddress>
            <streetAddress>770 Sydney St</streetAddress>
            <city>Sydney</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2000</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">1026.00</ReservePrice>
        <BiddingStartPrice currency="AUD">500.00</BiddingStartPrice>
        <BiddingIncrements>100</BiddingIncrements>
        <EndTime>2015-05-24-06:00</EndTime>
        <ID>faced800-d358-11e4-a715-0002a5d5c51b-27</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>FireTruck Toy</Title>
        <Category>Kids Toys</Category>
        <Picture>http://www.officeplayground.com/Assets/ProductImages/pi4000-4199/4109_FireTruckFoamStressToy_1a_i.jpg</Picture>
        <Description>Used condition but works great.</Description>
        <PostalAddress>
            <streetAddress>10 Eastern st</streetAddress>
            <city>Sydney</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2000</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">39.00</ReservePrice>
        <BiddingStartPrice currency="AUD">5.00</BiddingStartPrice>
        <BiddingIncrements>5</BiddingIncrements>
        <EndTime>2015-04-24-16:00</EndTime>
        <ID>f3fefea6-d443-11e4-b9d6-1861e6b88ec1-28</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Printing Papers</Title>
        <Category>Office Works</Category>
        <Picture>http://ecx.images-amazon.com/images/I/410GWriJ-mL._SL75_SS50_.jpg</Picture>
        <Description>Brand New Papers</Description>
        <PostalAddress>
            <streetAddress>5 Noth Cr</streetAddress>
            <city>Sydney</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2146</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">10.00</ReservePrice>
        <BiddingStartPrice currency="AUD">1.00</BiddingStartPrice>
        <BiddingIncrements>1</BiddingIncrements>
        <EndTime>2015-06-24-05:00</EndTime>
        <ID>falz5r70-pe18-12e4-a715-0002a5d5a51b-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Electronic Fan</Title>
        <Category>Electronics</Category>
        <Picture>http://www.appliance411.com/faq/fan-icon.50x50.gif</Picture>
        <Description>It is a very fast fan</Description>
        <PostalAddress>
            <streetAddress>3 Nookford Rd</streetAddress>
            <city>Sydney</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2016</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">200.00</ReservePrice>
        <BiddingStartPrice currency="AUD">50.00</BiddingStartPrice>
        <BiddingIncrements>40</BiddingIncrements>
        <EndTime>2015-09-24-06:00</EndTime>
        <ID>t4fef5t6-d443-u1e4-c3d6-1681e6b88ec1-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Sony Viao 2012</Title>
        <Category>Computers</Category>
        <Picture>http://www.avcj.com/IMG/852/281852/sonyvaio.jpg</Picture>
        <Description>awesome notebook, you must buy it</Description>
        <PostalAddress>
            <streetAddress>78 Little St</streetAddress>
            <city>Glenwood</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2768</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">800.00</ReservePrice>
        <BiddingStartPrice currency="AUD">100.00</BiddingStartPrice>
        <BiddingIncrements>10</BiddingIncrements>
        <EndTime>2015-04-24-7:00</EndTime>
        <ID>byred800-d358-0894-a715-jhgba5d5c51b-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Iphone 6</Title>
        <Category>Mobiles</Category>
        <Picture>http://cdn.macrumors.com/article-new/2014/04/iphone-6-side.jpg</Picture>
        <Description>Brand New SmartPhones</Description>
        <PostalAddress>
            <streetAddress>4 Harington St</streetAddress>
            <city>Stratfield</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2310</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">1000.00</ReservePrice>
        <BiddingStartPrice currency="AUD">100.00</BiddingStartPrice>
        <BiddingIncrements>100</BiddingIncrements>
        <EndTime>2015-09-01-2:00</EndTime>
        <ID>jg56fea6-uh53-11e4-b9d6-1681e6b88ec1-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Samsung Galaxy S4</Title>
        <Category>Mobiles</Category>
        <Picture>http://cdn.theunlockr.com/wp-content/uploads/2014/04/Flash-Recovery-Samsung-Galaxy-S4-Canadian.jpg</Picture>
        <Description>Used but Very nice phone</Description>
        <PostalAddress>
            <streetAddress>1 Hurley Dr</streetAddress>
            <city>Burwood</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2435</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">250.00</ReservePrice>
        <BiddingStartPrice currency="AUD">50.00</BiddingStartPrice>
        <BiddingIncrements>10</BiddingIncrements>
        <EndTime>2015-04-24-7:00</EndTime>
        <ID>67th5rdj-6y58-34e4-a715-7002a5d5cu8b-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Office Shirt</Title>
        <Category>Clothes</Category>
        <Picture>http://www.scottevest.com/mm5/graphics/00000001/p_camp_shirt_mango_zm.jpg</Picture>
        <Description>Its a brand new shirt, I am selling it as it does not fit me</Description>
        <PostalAddress>
            <streetAddress>7 High St</streetAddress>
            <city>Kensington</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2800</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">80.00</ReservePrice>
        <BiddingStartPrice currency="AUD">45.00</BiddingStartPrice>
        <BiddingIncrements>10</BiddingIncrements>
        <EndTime>2015-09-24-06:00</EndTime>
        <ID>hu67rt6g-d443-7ug4-9iy6-1ik7e6b88901-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Study Lamp</Title>
        <Category>Electronics</Category>
        <Picture>http://homesdir.net/wp-content/uploads/2014/12/black-desk-lamp-lamp.jpg</Picture>
        <Description>It works great</Description>
        <PostalAddress>
            <streetAddress>8 East Rd</streetAddress>
            <city>Lidcombe</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2178</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">15.00</ReservePrice>
        <BiddingStartPrice currency="AUD">1.00</BiddingStartPrice>
        <BiddingIncrements>1</BiddingIncrements>
        <EndTime>2015-09-24-06:00</EndTime>
        <ID>u7c8ug50-d8i8-1k84-y715-8i02a5d5ik1b-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>HSC Maths Textbook</Title>
        <Category>Education</Category>
        <Picture>http://upload.wikimedia.org/wikipedia/commons/6/63/Textbook.JPG</Picture>
        <Description>Super Dooper Phone</Description>
        <PostalAddress>
            <streetAddress>7 sad St</streetAddress>
            <city>Wentworthville</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2146</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">50.00</ReservePrice>
        <BiddingStartPrice currency="AUD">10.00</BiddingStartPrice>
        <BiddingIncrements>10</BiddingIncrements>
        <EndTime>2015-10-1-06:00</EndTime>
        <ID>7u6ef076-j743-y6e4-b9d6-7881e6b88ec1-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>HTC Desire 510</Title>
        <Category>Mobile Phones</Category>
        <Picture>http://www.htc.com/managed-assets/shared/desktop/smartphones/htc-desire-eye/htc-desire-eye-global-sketchfab-white.png</Picture>
        <Description>Best Phone</Description>
        <PostalAddress>
            <streetAddress>7 Udle Rd</streetAddress>
            <city>Melbourne</city>
            <state>Vic</state>
            <country>Australia</country>
            <postalCode>2543</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">1000.00</ReservePrice>
        <BiddingStartPrice currency="AUD">100.00</BiddingStartPrice>
        <BiddingIncrements>10</BiddingIncrements>
        <EndTime>2015-09-24-06:00</EndTime>
        <ID>ujhyd800-d358-11e4-a715-0002a5d5c51b-26</ID>
    </AuctionItem>
    <AuctionItem>
        <Title>Wine Glass</Title>
        <Category>Homeware</Category>
        <Picture>https://foodservice.libbey.com/var/libbey/storage/images/libbey-foodservice-home/product-repository/burgundy-wine-glass7/88452-1-eng-US/Burgundy-Wine-Glass.jpg</Picture>
        <Description>selling six of these wine glasses</Description>
        <PostalAddress>
            <streetAddress>67 Phillips St</streetAddress>
            <city>Lidcombe</city>
            <state>NSW</state>
            <country>Australia</country>
            <postalCode>2345</postalCode>
        </PostalAddress>
        <ReservePrice currency="AUD">25.00</ReservePrice>
        <BiddingStartPrice currency="AUD">1.00</BiddingStartPrice>
        <BiddingIncrements>10</BiddingIncrements>
        <EndTime>2015-04-24-7:00</EndTime>
        <ID>ik7hfea6-d443-11e4-b9d6-1681e6b88ec1-26</ID>
    </AuctionItem>
    <AuctionItem>
